
project_id = "mhhzdykyjgrnprcyhlbz"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:8080"
additional_redirect_urls = [
  "https://mhhzdykyjgrnprcyhlbz.supabase.co",
  "http://localhost:8080/reset-password"
]
jwt_expiry = 3600
